/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MealViewMealIdImport } from './routes/meal/view/$mealId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MealViewMealIdRoute = MealViewMealIdImport.update({
  id: '/meal/view/$mealId',
  path: '/meal/view/$mealId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/meal/view/$mealId': {
      id: '/meal/view/$mealId'
      path: '/meal/view/$mealId'
      fullPath: '/meal/view/$mealId'
      preLoaderRoute: typeof MealViewMealIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meal/view/$mealId': typeof MealViewMealIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meal/view/$mealId': typeof MealViewMealIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/meal/view/$mealId': typeof MealViewMealIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meal/view/$mealId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meal/view/$mealId'
  id: '__root__' | '/' | '/meal/view/$mealId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealViewMealIdRoute: typeof MealViewMealIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealViewMealIdRoute: MealViewMealIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/meal/view/$mealId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/meal/view/$mealId": {
      "filePath": "meal/view/$mealId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
