/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealViewMealIdRouteImport } from './routes/meal/view/$mealId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealViewMealIdRoute = MealViewMealIdRouteImport.update({
  id: '/meal/view/$mealId',
  path: '/meal/view/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meal/view/$mealId': typeof MealViewMealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meal/view/$mealId': typeof MealViewMealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meal/view/$mealId': typeof MealViewMealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meal/view/$mealId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meal/view/$mealId'
  id: '__root__' | '/' | '/meal/view/$mealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealViewMealIdRoute: typeof MealViewMealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/view/$mealId': {
      id: '/meal/view/$mealId'
      path: '/meal/view/$mealId'
      fullPath: '/meal/view/$mealId'
      preLoaderRoute: typeof MealViewMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealViewMealIdRoute: MealViewMealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
